
seed_questions = [
    ["What is the chemical symbol for gold?", ["Au", "Ag", "Cu", "Fe"], "Au", {"difficulty": "Easy"}],
    ["Who painted the Mona Lisa?", ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"], "Leonardo da Vinci", {"difficulty": "Easy"}],
    ["What is the currency used in Japan?", ["Yen", "Dollar", "Euro", "Pound"], "Yen", {"difficulty": "Easy"}],
    ["What is the tallest mammal?", ["Giraffe", "Elephant", "Hippopotamus", "Rhinoceros"], "Giraffe", {"difficulty": "Easy"}],
    ["Who wrote the novel 'To Kill a Mockingbird'?", ["Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald", "Maya Angelou"], "Harper Lee", {"difficulty": "Easy"}],
    ["What is the largest ocean on Earth?", ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], "Pacific Ocean", {"difficulty": "Easy"}],
    ["What is the capital city of Australia?", ["Sydney", "Melbourne", "Brisbane", "Canberra"], "Canberra", {"difficulty": "Easy"}],
    ["What is the capital of Italy?", ["Rome", "Milan", "Florence", "Venice"], "Rome", {"difficulty": "Easy"}],
    ["Who wrote 'Romeo and Juliet'?", ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], "William Shakespeare", {"difficulty": "Easy"}],
    ["Which planet is known as the 'Morning Star' or 'Evening Star'?", ["Mars", "Venus", "Mercury", "Saturn"], "Venus", {"difficulty": "Medium"}],
    ["Who was the first female Prime Minister of the United Kingdom?", ["Margaret Thatcher", "Theresa May", "Angela Merkel", "Jacinda Ardern"], "Margaret Thatcher", {"difficulty": "Medium"}],
    ["What is the term for a group of porcupines?", ["A prickle", "A quill", "A spike", "A herd"], "A prickle", {"difficulty": "Medium"}],
    ["In which year did the Titanic sink?", ["1912", "1908", "1920", "1915"], "1912", {"difficulty": "Medium"}],
    ["Which city hosted the 2016 Summer Olympics?", ["Rio de Janeiro", "London", "Beijing", "Tokyo"], "Rio de Janeiro", {"difficulty": "Medium"}],
    ["Which city has the highest population density?", ["Dhaka", "Mumbai", "Hong Kong", "Tokyo"], "Dhaka", {"difficulty": "Medium"}],
    ["Which artist painted 'Starry Night'?", ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], "Vincent van Gogh", {"difficulty": "Medium"}],
    ["Which country is famous for the Great Wall?", ["China", "Japan", "India", "Russia"], "China", {"difficulty": "Medium"}],
    ["What is the smallest prime number greater than 10?", ["11", "12", "13", "14"], "11", {"difficulty": "Medium"}],
    ["Who composed the 'Four Seasons'?", ["Antonio Vivaldi", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Johann Sebastian Bach"], "Antonio Vivaldi", {"difficulty": "Medium"}],
    ["Which ancient civilization built the city of Carthage?", ["Greeks", "Romans", "Phoenicians", "Persians"], "Phoenicians", {"difficulty": "Hard"}],
    ["What is the chemical symbol for the element Mercury?", ["Hg", "Me", "Mr", "Hy"], "Hg", {"difficulty": "Hard"}],
    ["Which country has the longest coastline?", ["Canada", "Russia", "Australia", "Brazil"], "Canada", {"difficulty": "Hard"}],
    ["Who was the first woman to win a Nobel Prize in Physics?", ["Marie Curie", "Maria Goeppert Mayer", "Dorothy Crowfoot Hodgkin", "Chien-Shiung Wu"], "Maria Goeppert Mayer", {"difficulty": "Hard"}],
    ["In which year was the Magna Carta signed?", ["1215", "1348", "1492", "1688"], "1215", {"difficulty": "Hard"}],
    ["In which country was the mathematician Euclid born?", ["Greece", "Italy", "Egypt", "France"], "Egypt", {"difficulty": "Hard"}],
    ["What is the capital of Mongolia?", ["Ulaanbaatar", "Kuala Lumpur", "Bangkok", "Hanoi"], "Ulaanbaatar", {"difficulty": "Hard"}],
    ["Which is the largest desert in the world?", ["Antarctica", "Sahara", "Gobi", "Arabian"], "Antarctica", {"difficulty": "Hard"}],
    ["What is the tallest mountain in Africa?", ["Kilimanjaro", "Everest", "Denali", "K2"], "Kilimanjaro", {"difficulty": "Hard"}],
    ["Who discovered penicillin?", ["Alexander Fleming", "Marie Curie", "Louis Pasteur", "Jonas Salk"], "Alexander Fleming", {"difficulty": "Hard"}]
]

