from models.question import *

question1 = Question(question = "What is the largest planet in our solar system?", answers = ["Jupiter", "Saturn", "Mars", "Venus"], correct_answer= "Jupiter", difficulty="Easy")
question2 = Question(question = "What is the chemical symbol for gold?", answers = ["Au", "Ag", "Cu", "Fe"], correct_answer= "Au", difficulty="Easy")
question3 = Question(question = "Who painted the Mona Lisa?", answers = ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"], correct_answer= "Leonardo da Vinci", difficulty="Easy")
question4 = Question(question = "What is the currency used in Japan?", answers = ["Yen", "Dollar", "Euro", "Pound"], correct_answer= "Yen", difficulty="Easy")
question5 = Question(question = "What is the tallest mammal?", answers = ["Giraffe", "Elephant", "Hippopotamus", "Rhinoceros"], correct_answer= "Giraffe", difficulty="Easy")
question6 = Question(question = "Who wrote the novel 'To Kill a Mockingbird'?", answers = ["Harper Lee", "Ernest Hemingway", "F. Scott Fitzgerald", "Maya Angelou"], correct_answer= "Harper Lee", difficulty="Easy")
question7 = Question(question = "What is the largest ocean on Earth?", answers = ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correct_answer= "Pacific Ocean", difficulty="Easy")
question8 = Question(question = "What is the capital city of Australia?", answers = ["Sydney", "Melbourne", "Brisbane", "Canberra"], correct_answer= "Canberra", difficulty="Easy")
question9 = Question(question="What is the capital of Italy?", answers=["Rome", "Milan", "Florence", "Venice"], correct_answer="Rome", difficulty="Easy")
question10 = Question(question="Who wrote 'Romeo and Juliet'?", answers=["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], correct_answer="William Shakespeare", difficulty="Easy")

question11 = Question(question="Which planet is known as the 'Morning Star' or 'Evening Star'?", answers=["Mars", "Venus", "Mercury", "Saturn"], correct_answer="Venus", difficulty="Medium")
question12 = Question(question="Who was the first female Prime Minister of the United Kingdom?", answers=["Margaret Thatcher", "Theresa May", "Angela Merkel", "Jacinda Ardern"], correct_answer="Margaret Thatcher", difficulty="Medium")
question13 = Question(question="What is the term for a group of porcupines?", answers=["A prickle", "A quill", "A spike", "A herd"], correct_answer="A prickle", difficulty="Medium")
question14 = Question(question="In which year did the Titanic sink?", answers=["1912", "1908", "1920", "1915"], correct_answer="1912", difficulty="Medium")
question15 = Question(question="Which city hosted the 2016 Summer Olympics?", answers=["Rio de Janeiro", "London", "Beijing", "Tokyo"], correct_answer="Rio de Janeiro", difficulty="Medium")
question16 = Question(question="Which city has the highest population density?", answers=["Dhaka", "Mumbai", "Hong Kong", "Tokyo"], correct_answer="Dhaka", difficulty="Medium")
question17 = Question(question="Which artist painted 'Starry Night'?", answers=["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correct_answer="Vincent van Gogh", difficulty="Medium")
question18 = Question(question="Which country is famous for the Great Wall?", answers=["China", "Japan", "India", "Russia"], correct_answer="China", difficulty="Medium")
question19 = Question(question="What is the smallest prime number greater than 10?", answers=["11", "12", "13", "14"], correct_answer="11", difficulty="Medium")
question20 = Question(question="Who composed the 'Four Seasons'?", answers=["Antonio Vivaldi", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Johann Sebastian Bach"], correct_answer="Antonio Vivaldi", difficulty="Medium")

question21 = Question(question="Which ancient civilization built the city of Carthage?", answers=["Greeks", "Romans", "Phoenicians", "Persians"], correct_answer="Phoenicians", difficulty="Hard")
question22 = Question(question="What is the chemical symbol for the element Mercury?", answers=["Hg", "Me", "Mr", "Hy"], correct_answer="Hg", difficulty="Hard")
question23 = Question(question="Which country has the longest coastline?", answers=["Canada", "Russia", "Australia", "Brazil"], correct_answer="Canada", difficulty="Hard")
question20 = Question(question="Who was the first woman to win a Nobel Prize in Physics?", answers=["Marie Curie", "Maria Goeppert Mayer", "Dorothy Crowfoot Hodgkin", "Chien-Shiung Wu"], correct_answer="Maria Goeppert Mayer", difficulty="Hard")
question25 = Question(question="In which year was the Magna Carta signed?", answers=["1215", "1348", "1492", "1688"], correct_answer="1215", difficulty="Hard")
question26 = Question(question="In which country was the mathematician Euclid born?", answers=["Greece", "Italy", "Egypt", "France"], correct_answer="Egypt", difficulty="Hard")
question27 = Question(question="What is the capital of Mongolia?", answers=["Ulaanbaatar", "Kuala Lumpur", "Bangkok", "Hanoi"], correct_answer="Ulaanbaatar", difficulty="Hard")
question28 = Question(question="Which is the largest desert in the world?", answers=["Antarctica", "Sahara", "Gobi", "Arabian"], correct_answer="Antarctica", difficulty="Hard")
question29 = Question(question="What is the tallest mountain in Africa?", answers=["Kilimanjaro", "Everest", "Denali", "K2"], correct_answer="Kilimanjaro", difficulty="Hard")
question30 = Question(question="Who discovered penicillin?", answers=["Alexander Fleming", "Marie Curie", "Louis Pasteur", "Jonas Salk"], correct_answer="Alexander Fleming", difficulty="Hard")